name: 'Continuous Delivery'

# TODO: Change it
on:
  push:
    branches:
      - feature/ci_cd

env:
  SERVICE: 'latam-flight-delay-api'
  REPO_NAME: 'latam_repo'

jobs:
  job_id:
    runs-on: ubuntu-latest
    environment: latam_env

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: 'actions/checkout@v4'

    - name: GCP Authentication
      uses: 'google-github-actions/auth@v3'
      with:
        workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT }}'
        token_format: 'access_token'

    - name: Deploy to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v3'
      with:
          service: ${{ env.SERVICE }}
          region: ${{ secrets.REGION }}
          image: "${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"

    - name: Use output
      run: 'curl "${{ steps.deploy.outputs.url }}/health"'
